blank_issues_enabled: true
contact_links:
  - name: python-simplemachinesforum documentation
    url: https://oliver-zehentleitner.github.io/python-simplemachinesforum/
    about: The complete UNICORN Binance Suite documentation.
  - name: Get Professional and Fast Support
    url: https://www.lucit.tech/get-support.html
    about: Contact the LUCIT Development Team.
